### PR TITLE
resolve mpetazzoni/ttorrent#144 remove depends of apache-comons-cedec

### PR DESCRIPTION
**Pull request by d3roch4**
this implementation is work for me

### CODE REVIEW

**Comment by mpetazzoni** [comment]
Hmm, there's quite a bit of stuff in there. What change exactly are you trying to get upstream?

**Comment by d3roch4** [comment]
This change are for use in Android OS, the main change is in the file: core/src/main/java/com/turn/ttorrent/common/Torrent.java 
The gradle files maybe should not be sent...

**Comment by mpetazzoni** [comment]
Indeed. Can you rework your PR to only contain the changes relevant to your fix?

**Comment by d3roch4** [comment]
Good Morning!
I do not know how to do that when I send a PR github already has my entire branch ...
I qero leave .gladre files in my business because AndroidStudio does not use pon.xml

**Comment by henkel** [comment]
Isolated PR for "resolve mpetazzoni/ttorrent#144 remove depends of apache-comons-cedec" is available in PR #161. 
I will maintain the gradle configuration for Android in a dedicated branch: https://github.com/henkel/ttorrent-android

**Pull request closed without merging**
