### PR TITLE
Remove dependency on Apache comons-codec

### PR DESCRIPTION
**Pull request by henkel**
Isolated PR with Andre's fixes for mpetazzoni/ttorrent#144

### CODE REVIEW

**Comment by henkel** [comment]
This is PR #146 minus the gradle configuration for Android

**Comment by mpetazzoni** [comment]
Thanks! I have a few comments though

**Comment by henkel** [comment]
Good proposals! I reworked the original PR and pushed a new one. NoSuchAlgorithmException is now propagated and that's why more files are affected.

**Comment by mpetazzoni** [comment]
Thanks, just two little things left that you missed

**Comment by henkel** [comment]
Oops, somehow I messed up the rebase. Thanks for the quick feedback - it should be fine now.

**Comment by mpetazzoni** [comment]
Thanks!

**Pull request merged**
