### PR TITLE
correct README pom dependency

### PR DESCRIPTION
**Pull request by wangdengwu**

### CODE REVIEW

**Comment by cjmalloy** [comment]
The artifact id ttorrent-core should be correct. Were you having any issues with this artifact id?

**Comment by wangdengwu** [comment]
i searched ttorrent at http://search.maven.org/ and got the result is 
<dependency>
    <groupId>com.turn</groupId>
    <artifactId>ttorrent</artifactId>
    <version>1.4</version>
</dependency>
and i also use ttorrent-core in my local project, but maven can't find it.so i change it to ttorrent, it works for me.so i think may be the right one is ttorrent
cheers.

**Comment by cjmalloy** [comment]
It just changed recently for 1.5. There was a re-org but no release yet so it's not available in maven central.

You should still use the old way (ttorrent) for 1.4, change to ttorrent-core for 1.5.

**Comment by wangdengwu** [comment]
Thanks cjmalloy.

**Comment by tchoulihan** [comment]
This is still broken. 

This doesn't work:
```
		<dependency>
			<groupId>com.turn</groupId>
			<artifactId>ttorrent-core</artifactId>
			<version>1.5</version>
		</dependency>
```

This does work:
```
		<dependency>
			<groupId>com.turn</groupId>
			<artifactId>ttorrent</artifactId>
			<version>1.4</version>
		</dependency>

```

Also, I tried using the JBOSS repo to use the snapshot version, but its also missing, or has never been deployed.

**Comment by cjmalloy** [comment]
Maybe we should do a release so people stop having this issue.

**Comment by mpetazzoni** [comment]
Yes. I'll try to find some time to do it soon.

**Comment by henkel** [comment]
@mpetazzoni, do you have any plans to release 1.5 soon?
I'm working on a small Android library that has an upstream dependency on ttorrent. Version 1.4 is not compatible to Android and in general it would be great to have more frequent library releases.
At the moment my fork [ttorrent-android ](https://github.com/henkel/ttorrent-android) is identical to ttorrent master with the exception of some Android build files. So far I provided my changes as pull requests to you and would like to continue that way. If you do not have time I could publish releases from my fork and name them ttorrent-android. Any thoughts?

**Comment by henkel** [comment]
Thanks much for release 1.5 - highly appreciated!!

**Comment by mpetazzoni** [comment]
You're welcome. It was way overdue :)

**Pull request closed without merging**
