### PR TITLE
Refactored out dependency on log4j.

### PR DESCRIPTION
**Pull request by cjmalloy**
There are now two submodules in this project, cli and core.

### CODE REVIEW

**Comment by mpetazzoni** [comment]
Looks great! Thanks! This will probably warrant a new point release to deploy new JARs to Maven Central.

**Comment by mpetazzoni** [comment]
By the way, would you mind updating the README with the correct POM info in the example?

**Comment by cjmalloy** [comment]
Here is the readme pull: https://github.com/mpetazzoni/ttorrent/pull/121

**Comment by cjmalloy** [comment]
You may also have noticed that I commented out the dependency for testng.
I was not sure if it was being used, since there were no errors removing it.
Let me know if we should add it back in or delete the comment.

**Comment by cjmalloy** [comment]
Re: testng- I just realized the test folder is incorrect. The test folder should be src/test/java/ and then the dependency will be required.

**Comment by mpetazzoni** [comment]
Yep, mind fixing this too? Thanks!

**Comment by icemagno** [comment]
Thanks all for the efforts. I'll try to embedd this version in my web application, so I can remove my fork.

**Pull request merged**
