### PR TITLE
fix bug by which not all peers that the server reports are reported b…

### PR DESCRIPTION
**Pull request by halfmanhalffish**
…ack to clients

### CODE REVIEW

**Comment by mpetazzoni** [comment]
Thanks, can you squash the commits together and fix the indentation of your change? I'm surprised the for loop condition doesn't work as expected.

**Comment by halfmanhalffish** [comment]
Hi Maxime,

As I understand it if I were to squash commits on a repository that's
already been pushed it would put git into an inconsistent state.  If it's
possible to squash directly on github that could be made to work.  I'll
have a look.

I'll alter the tabs to spaces today.

Philip

**Comment by halfmanhalffish** [comment]
Ready to pull now.
I'm surprised at this bug too.  I thought initially it might be a floating point problem like you often get with FP, you know because of IEEE representation you can divide 6 by 3 and get 2.9777777777777 recurring.  But the debugger showed a correct integer result so I'm presuming that's not the problem.

**Comment by mpetazzoni** [comment]
@halfmanhalffish Force-push is only an issue if you are doing it on a branch that other people have pulled down. In the case of a pull request, it's fairly safe to rewrite the branch the pull request is based on.

I'm as surprised as you are by the bug. When you debugged it, what values did you see for `data.remaining()`, and for `data.remaining() / 6`? I don't understand how it would skip the loop completely when `i = 0`, since clearly `0 < (data.remaining() / 6) = 1`.

**Comment by halfmanhalffish** [comment]
Ah !  After looking at it a second time the answer is rather more clear.
Firstly I don't think I explained the scenario to you properly.  It fails
when there is more than one peer to report.  The fault is that on each
iteration of the for loop i goes up by one AND data.remaining() goes down
by 1 (6 bytes).  So on the second iteration i is 1 and data.remaining() / 6
is 1.  If the loop had used <= instead of < then the second iteration would
have worked (but the 3rd and later wouldn't have).

**Comment by mpetazzoni** [comment]
Ah, makes more sense; thanks.

**Pull request merged**
